# Generated by Django 5.2.16 on 2026-07-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_tool_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDLAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('source_filename', models.CharField(max_length=512)),
                ('lifecycle', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('migrating', 'Migrating'), ('retired', 'Retired')], default='active', max_length=16)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='WDLTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WDLSourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('import', 'Imported'), ('edit', 'Edited'), ('format', 'Formatted')], max_length=16)),
                ('content', models.TextField()),
                ('digest', models.CharField(max_length=80)),
                ('diff', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(default='local-user', max_length=256)),
                ('analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_revisions', to='workflows.wdlasset')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='WDLAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('actor', models.CharField(default='local-user', max_length=256)),
                ('note', models.TextField(blank=True)),
                ('changes', models.JSONField(default=dict)),
                ('diff', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workflows.wdlasset')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workflows.wdlsourcerevision')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='wdlasset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='wdl_assets', to='workflows.wdltag'),
        ),
        migrations.AddConstraint(
            model_name='wdlsourcerevision',
            constraint=models.UniqueConstraint(fields=('asset', 'version'), name='unique_wdl_asset_source_revision'),
        ),
    ]
