# Generated by Django 5.2.16 on 2026-08-12 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_workflow_maintainer_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True, max_length=2048)),
                ('source_repository', models.CharField(blank=True, max_length=512)),
                ('license', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('lifecycle', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('metadata_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('updated_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('actor', models.CharField(default='local-user', max_length=256)),
                ('changes', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('container_images', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('metadata_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolSoftwareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('dependency', 'Dependency'), ('runtime', 'Runtime')], default='primary', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'software__name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='analysisrun',
            name='analysis_run_has_one_source',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='run_kind',
            field=models.CharField(choices=[('workflow', 'Workflow analysis'), ('tool_test', 'Tool test')], db_index=True, default='workflow', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='tool_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='workflows.toolversion'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('run_kind', 'workflow'), ('tool_version__isnull', True), models.Q(models.Q(('asset__isnull', False), ('revision__isnull', False), ('workflow_version__isnull', True)), models.Q(('asset__isnull', True), ('revision__isnull', True), ('workflow_version__isnull', False)), _connector='OR')), models.Q(('asset__isnull', True), ('revision__isnull', True), ('run_kind', 'tool_test'), ('tool_version__isnull', False), ('workflow_version__isnull', True)), _connector='OR'), name='analysis_run_has_one_source'),
        ),
        migrations.AddField(
            model_name='softwareauditevent',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workflows.softwareasset'),
        ),
        migrations.AddField(
            model_name='softwarerelease',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='workflows.softwareasset'),
        ),
        migrations.AddField(
            model_name='softwareauditevent',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='workflows.softwarerelease'),
        ),
        migrations.AddField(
            model_name='toolsoftwarelink',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_links', to='workflows.softwarerelease'),
        ),
        migrations.AddField(
            model_name='toolsoftwarelink',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_links', to='workflows.softwareasset'),
        ),
        migrations.AddField(
            model_name='toolsoftwarelink',
            name='tool_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_links', to='workflows.toolversion'),
        ),
        migrations.AddConstraint(
            model_name='softwarerelease',
            constraint=models.UniqueConstraint(fields=('software', 'version'), name='unique_software_release'),
        ),
        migrations.AddConstraint(
            model_name='toolsoftwarelink',
            constraint=models.UniqueConstraint(fields=('tool_version', 'software', 'role'), name='unique_tool_software_role'),
        ),
    ]
