# Generated by Django 5.2.16 on 2026-08-12 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_softwareasset_softwareauditevent_softwarerelease_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(max_length=16, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='error_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='error_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='error_retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='external_analysis_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='external_run_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='output_manifest',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='output_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete'), ('unavailable', 'Unavailable')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='request_digest',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retries', to='workflows.analysisrun'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='status_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('running', 'Running'), ('cancel_requested', 'Cancel requested'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='service_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='workflows.serviceaccount'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('service_account__isnull', False), models.Q(('external_run_id', ''), _negated=True)), fields=('service_account', 'external_run_id'), name='unique_service_external_run'),
        ),
        migrations.AddConstraint(
            model_name='analysisrun',
            constraint=models.UniqueConstraint(condition=models.Q(('service_account__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('service_account', 'idempotency_key'), name='unique_service_idempotency_key'),
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='service_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='workflows.serviceaccount'),
        ),
    ]
