# Generated by Django 5.2.16 on 2026-08-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_serviceaccount_servicetoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResourceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='default', max_length=64, unique=True)),
                ('document', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('digest', models.CharField(max_length=80)),
                ('created_by', models.CharField(default='local-user', max_length=256)),
                ('updated_by', models.CharField(default='local-user', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResourceCatalogRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=80)),
                ('document', models.JSONField(default=dict)),
                ('actor', models.CharField(default='local-user', max_length=256)),
                ('note', models.TextField(blank=True)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='workflows.analysisresourcecatalog')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'version'), name='unique_analysis_resource_catalog_revision')],
            },
        ),
    ]
