# Generated by Django 5.2.16 on 2026-08-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_analysis_resource_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WDLReviewThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('line', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by_name', models.CharField(max_length=256)),
                ('resolved_by_name', models.CharField(blank=True, max_length=256)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_threads', to='workflows.wdlasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wdl_review_threads', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_wdl_review_threads', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_threads', to='workflows.wdlsourcerevision')),
            ],
            options={
                'ordering': ['status', 'file_path', 'line', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WDLReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wdl_review_comments', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='workflows.wdlreviewthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WDLSourceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=256)),
                ('base_version', models.PositiveIntegerField()),
                ('base_digest', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_conflicts', to='workflows.wdlasset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wdl_source_conflicts', to=settings.AUTH_USER_MODEL)),
                ('current_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_conflicts', to='workflows.wdlsourcerevision')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WDLReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('requester_name', models.CharField(max_length=256)),
                ('assignee_name', models.CharField(max_length=256)),
                ('request_note', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('concluded_by_name', models.CharField(blank=True, max_length=256)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_requests', to='workflows.wdlasset')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wdl_reviews', to=settings.AUTH_USER_MODEL)),
                ('concluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concluded_wdl_reviews', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_wdl_reviews', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_requests', to='workflows.wdlsourcerevision')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('revision',), name='unique_pending_wdl_revision_review')],
            },
        ),
        migrations.AddConstraint(
            model_name='wdlreviewthread',
            constraint=models.CheckConstraint(condition=models.Q(('line__gte', 1)), name='wdl_review_thread_line_positive'),
        ),
        migrations.AddConstraint(
            model_name='wdlsourceconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('asset', 'actor'), name='unique_open_wdl_source_conflict'),
        ),
    ]
