# Generated by Django 5.2.16 on 2026-08-13 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_wdlreviewthread_wdlreviewcomment_wdlsourceconflict_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawdataScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_key', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('limited', 'Limited'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('trigger', models.CharField(default='scheduled', max_length=24)),
                ('actor', models.CharField(default='system', max_length=256)),
                ('progress', models.JSONField(default=dict)),
                ('catalog', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('scanned_entry_count', models.PositiveIntegerField(default=0)),
                ('scan_limited', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('root_key',), name='unique_active_rawdata_scan')],
            },
        ),
        migrations.CreateModel(
            name='RawdataDatasetIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_key', models.CharField(db_index=True, max_length=80)),
                ('dataset_id', models.CharField(max_length=64)),
                ('pair_key', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=256)),
                ('directory', models.CharField(max_length=1024)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('issues', models.JSONField(default=list)),
                ('files', models.JSONField(default=list)),
                ('total_size', models.BigIntegerField(default=0)),
                ('identity_digest', models.CharField(max_length=80)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('last_changed_at', models.DateTimeField()),
                ('last_scan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='workflows.rawdatascan')),
            ],
            options={
                'ordering': ['directory', 'name', 'dataset_id'],
            },
        ),
        migrations.CreateModel(
            name='RawdataDatasetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24)),
                ('actor', models.CharField(default='system', max_length=256)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawdata_events', to='workflows.analysisrun')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='workflows.rawdatadatasetindex')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_events', to='workflows.rawdatascan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RawdataRunReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_references', to='workflows.rawdatadatasetindex')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rawdata_references', to='workflows.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'run'), name='unique_rawdata_dataset_run_reference')],
            },
        ),
        migrations.AddConstraint(
            model_name='rawdatadatasetindex',
            constraint=models.UniqueConstraint(fields=('root_key', 'dataset_id'), name='unique_rawdata_dataset_index'),
        ),
    ]
