# Generated by Django 5.2.16 on 2026-08-13 05:54

import django.db.models.deletion
import workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0024_rawdatascan_rawdatadatasetindex_rawdatadatasetevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDLReleasePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='default', max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled_checks', models.JSONField(default=workflows.models.default_wdl_release_checks)),
                ('max_input_bytes', models.BigIntegerField(default=1073741824)),
                ('updated_by', models.CharField(default='system', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='WDLReleaseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=16)),
                ('policy_version', models.PositiveIntegerField()),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('checks', models.JSONField(default=list)),
                ('requested_by', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wdl_release_checks', to='workflows.analysisrun')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_checks', to='workflows.wdlasset')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_checks', to='workflows.wdlsourcerevision')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WDLAssetRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('actor', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='workflows.wdlasset')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='workflows.wdlsourcerevision')),
                ('release_check', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release', to='workflows.wdlreleasecheck')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'version'), name='unique_wdl_asset_release_version'), models.UniqueConstraint(fields=('asset', 'revision'), name='unique_wdl_asset_release_revision')],
            },
        ),
    ]
