# Generated by Django 5.2.16 on 2026-08-13 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_wdlreleasepolicy_wdlreleasecheck_wdlassetrelease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wdlsourceconflict',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True), ('assigned_to__isnull', False)), fields=('asset', 'assigned_to'), name='unique_assigned_open_wdl_source_conflict'),
        ),
    ]
