# Generated by Django 5.2.16 on 2026-08-30 05:49

import django.db.models.deletion
import django.utils.timezone
import uuid
import workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_analysisproduct_analysisproductversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('status_version', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='workflows.analysisrun')),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='workflows.serviceaccount')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField(max_length=2048)),
                ('secret_salt', models.UUIDField(editable=False)),
                ('secret_version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('dead_letter', 'Dead letter')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('last_response_excerpt', models.TextField(blank=True)),
                ('last_replayed_at', models.DateTimeField(blank=True, null=True)),
                ('last_replayed_by', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='workflows.integrationoutboxevent')),
            ],
            options={
                'ordering': ['next_attempt_at', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('replay_number', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('started', 'Started'), ('delivered', 'Delivered'), ('retry', 'Retry scheduled'), ('dead_letter', 'Dead letter'), ('lease_expired', 'Lease expired')], default='started', max_length=16)),
                ('request_timestamp', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolved_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='workflows.webhookdelivery')),
            ],
            options={
                'ordering': ['delivery_id', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=128)),
                ('url', models.URLField(max_length=2048)),
                ('event_types', models.JSONField(default=workflows.models.default_webhook_event_types)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_salt', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('secret_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.CharField(default='deployment', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_endpoints', to='workflows.serviceaccount')),
            ],
            options={
                'ordering': ['service_account_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='workflows.webhookendpoint'),
        ),
        migrations.AddIndex(
            model_name='integrationoutboxevent',
            index=models.Index(fields=['service_account', 'created_at'], name='outbox_service_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.UniqueConstraint(fields=('run', 'event_type', 'status_version'), name='unique_run_outbox_status_event'),
        ),
        migrations.AddConstraint(
            model_name='webhookdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='unique_webhook_delivery_attempt'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(fields=('service_account', 'name'), name='unique_service_webhook_endpoint'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['state', 'next_attempt_at'], name='webhook_delivery_due_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['state', 'lease_expires_at'], name='webhook_delivery_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'endpoint'), name='unique_event_endpoint_delivery'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('state', 'delivering')), models.Q(models.Q(('state', 'delivering'), _negated=True), ('lease_expires_at__isnull', True), ('lease_token__isnull', True)), _connector='OR'), name='webhook_delivery_lease_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'delivered'), _negated=True), ('delivered_at__isnull', False), _connector='OR'), name='webhook_delivery_has_delivered_at'),
        ),
    ]
