# Generated by Django 5.2.16 on 2026-08-30 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_staging_coordinator(apps, schema_editor):
    coordinator = apps.get_model("workflows", "InputStagingCoordinator")
    coordinator.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_integrationoutboxevent_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputStagingCoordinator',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputStagingLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_lease_token', models.UUIDField(editable=False)),
                ('reserved_bytes', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_staging_lease', to='workflows.analysisrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_bytes__gt', 0)), name='input_staging_lease_positive_bytes')],
            },
        ),
        migrations.RunPython(create_staging_coordinator, migrations.RunPython.noop),
    ]
