# Generated by Django 5.2.16 on 2026-08-30 10:29

import django.db.models.deletion
import django.db.models.functions
import django.utils.timezone
import uuid
from django.db import migrations, models


def populate_outbox_deduplication_keys(apps, schema_editor):
    del schema_editor
    events = apps.get_model("workflows", "IntegrationOutboxEvent")
    events.objects.update(
        deduplication_key=django.db.models.functions.Concat(
            models.Value("status:"),
            django.db.models.functions.Cast(
                models.F("status_version"),
                output_field=models.CharField(),
            ),
        )
    )


def clear_outbox_deduplication_keys(apps, schema_editor):
    del schema_editor
    events = apps.get_model("workflows", "IntegrationOutboxEvent")
    events.objects.all().update(deduplication_key="")


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0030_inputstagingcoordinator_inputstaginglease'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisOutputRetention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retain_until', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('protected', 'Protected'), ('cleaning', 'Cleaning'), ('cleaned', 'Cleaned'), ('failed', 'Cleanup failed')], db_index=True, default='protected', max_length=16)),
                ('cleanup_attempt_count', models.PositiveIntegerField(default=0)),
                ('cleanup_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('cleanup_path_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('cleanup_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['retain_until', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=80)),
                ('source_manifest_digest', models.CharField(max_length=80)),
                ('target_profile', models.CharField(max_length=64)),
                ('target_snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('exporting', 'Exporting'), ('succeeded', 'Succeeded'), ('dead_letter', 'Dead letter')], db_index=True, default='pending', max_length=16)),
                ('manifest', models.JSONField(default=dict)),
                ('manifest_digest', models.CharField(blank=True, max_length=80)),
                ('manifest_completed_at', models.DateTimeField(blank=True, null=True)),
                ('manifest_location', models.JSONField(default=dict)),
                ('requires_ack', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=256)),
                ('acknowledgement', models.JSONField(default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('replay_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_retryable', models.BooleanField(default=False)),
                ('last_replayed_at', models.DateTimeField(blank=True, null=True)),
                ('last_replayed_by', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_attempt_at', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactExportAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('replay_number', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('retry', 'Retry scheduled'), ('dead_letter', 'Dead letter'), ('lease_expired', 'Lease expired')], default='started', max_length=16)),
                ('files_total', models.PositiveIntegerField(default=0)),
                ('files_exported', models.PositiveIntegerField(default=0)),
                ('bytes_exported', models.PositiveBigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['export_id', 'attempt_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='integrationoutboxevent',
            name='unique_run_outbox_status_event',
        ),
        migrations.AddField(
            model_name='integrationoutboxevent',
            name='deduplication_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.RunPython(
            populate_outbox_deduplication_keys,
            clear_outbox_deduplication_keys,
        ),
        migrations.AlterField(
            model_name='integrationoutboxevent',
            name='deduplication_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.UniqueConstraint(fields=('run', 'event_type', 'deduplication_key'), name='unique_run_outbox_deduplication_key'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('deduplication_key', ''), _negated=True), name='outbox_deduplication_key_not_empty'),
        ),
        migrations.AddField(
            model_name='analysisoutputretention',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_retention', to='workflows.analysisrun'),
        ),
        migrations.AddField(
            model_name='artifactexport',
            name='retention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_exports', to='workflows.analysisoutputretention'),
        ),
        migrations.AddField(
            model_name='artifactexport',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_exports', to='workflows.analysisrun'),
        ),
        migrations.AddField(
            model_name='artifactexport',
            name='service_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_exports', to='workflows.serviceaccount'),
        ),
        migrations.AddField(
            model_name='artifactexportattempt',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='workflows.artifactexport'),
        ),
        migrations.AddConstraint(
            model_name='analysisoutputretention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cleanup_expires_at__isnull', False), ('cleanup_token__isnull', False), ('state', 'cleaning')), models.Q(models.Q(('state', 'cleaning'), _negated=True), ('cleanup_expires_at__isnull', True), ('cleanup_token__isnull', True)), _connector='OR'), name='output_retention_cleanup_lease_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='analysisoutputretention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'cleaned'), _negated=True), ('cleaned_at__isnull', False), _connector='OR'), name='output_retention_cleaned_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='analysisoutputretention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'cleaned'), _negated=True), ('quarantined_at__isnull', False), _connector='OR'), name='output_retention_cleaned_was_quarantined'),
        ),
        migrations.AddIndex(
            model_name='artifactexport',
            index=models.Index(fields=['state', 'next_attempt_at'], name='artifact_export_due_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactexport',
            index=models.Index(fields=['state', 'lease_expires_at'], name='artifact_export_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='artifactexport',
            constraint=models.UniqueConstraint(fields=('service_account', 'idempotency_key'), name='unique_service_artifact_export_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='artifactexport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('state', 'exporting')), models.Q(models.Q(('state', 'exporting'), _negated=True), ('lease_expires_at__isnull', True), ('lease_token__isnull', True)), _connector='OR'), name='artifact_export_lease_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='artifactexport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='artifact_export_success_has_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='artifactexport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), ('manifest_completed_at__isnull', False), _connector='OR'), name='artifact_export_success_has_manifest_time'),
        ),
        migrations.AddConstraint(
            model_name='artifactexport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'succeeded'), _negated=True), models.Q(('manifest_digest', ''), _negated=True), _connector='OR'), name='artifact_export_success_has_manifest_digest'),
        ),
        migrations.AddConstraint(
            model_name='artifactexport',
            constraint=models.CheckConstraint(condition=models.Q(('acknowledged_at__isnull', True), ('state', 'succeeded'), _connector='OR'), name='artifact_export_ack_requires_success'),
        ),
        migrations.AddConstraint(
            model_name='artifactexportattempt',
            constraint=models.UniqueConstraint(fields=('export', 'attempt_number'), name='unique_artifact_export_attempt'),
        ),
    ]
