# Generated by Django 5.2.16 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0031_analysisoutputretention_artifactexport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowPackageAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("sigstore", "Sigstore"),
                            ("bundled", "Signed application bundle"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_digest", models.CharField(max_length=80)),
                ("statement_digest", models.CharField(max_length=80)),
                ("signature_bundle_digest", models.CharField(blank=True, max_length=80)),
                ("signer_identity", models.CharField(max_length=512)),
                ("verified_by", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_attestation",
                        to="workflows.workflowversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(source_digest="")
                            & ~models.Q(statement_digest="")
                            & ~models.Q(signer_identity="")
                        ),
                        name="workflow_package_attestation_has_evidence",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(verification_method="bundled")
                            | ~models.Q(signature_bundle_digest="")
                        ),
                        name="workflow_package_sigstore_has_bundle",
                    ),
                ],
            },
        ),
    ]
