# Generated by Django 5.2.16 on 2026-09-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_workflowpackageattestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='execution_engine',
            field=models.CharField(choices=[('miniwdl', 'MiniWDL'), ('nextflow', 'Nextflow')], db_index=True, default='miniwdl', max_length=16),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='runtime_manifest',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='execution_engine',
            field=models.CharField(choices=[('miniwdl', 'MiniWDL'), ('nextflow', 'Nextflow')], db_index=True, default='miniwdl', max_length=16),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='runtime_manifest',
            field=models.JSONField(default=dict),
        ),
    ]
