# Generated by Django 5.2.16 on 2026-09-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_analysisrun_execution_engine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawdataBatchReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_key', models.CharField(max_length=80)),
                ('directory', models.CharField(max_length=1024)),
                ('generation', models.CharField(max_length=80)),
                ('inventory_digest', models.CharField(max_length=80)),
                ('changed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('root_key', 'directory'), name='unique_rawdata_batch_readiness')],
            },
        ),
    ]
