services:
  backend:
    environment:
      DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,[::1],wdl.qzhqzh.com},bioworkflow-api"
    networks:
      default: {}
      bioworkflow-integration:
        aliases:
          - bioworkflow-api

networks:
  bioworkflow-integration:
    name: ${BIOWORKFLOW_INTEGRATION_NETWORK:-bioworkflow-integration}
    external: true
